#numpy : packages for mutlidimensional array 

In [1]:
import numpy as np

In [2]:
list=[4,8,12]
np.array(list)

array([ 4,  8, 12])

In [50]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [7]:
list_of_lists=[[1,3,5],[2,4,6],[2,3,5]]
np.array(list_of_lists)

array([[1, 3, 5],
       [2, 4, 6],
       [2, 3, 5]])

In [8]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(1,50)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [10]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros(4,int)

array([0, 0, 0, 0])

In [13]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.ones((3,4),int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [18]:
np.linspace(0,2,4)

array([0.        , 0.66666667, 1.33333333, 2.        ])

In [19]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [44]:
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [21]:
np.random.rand(2,5)

array([[0.587365  , 0.4247465 , 0.77580179, 0.62334395, 0.7365423 ],
       [0.34073697, 0.22092896, 0.70854912, 0.25173116, 0.85729669]])

In [22]:
np.random.randn(2,5)

array([[ 1.67121421, -0.09871977, -2.10768547, -0.71621055, -1.03709096],
       [ 1.59467414,  2.10328186, -0.71006634,  0.45832432, -1.67720782]])

In [23]:
ar=np.random.randn(2,4)
ar

array([[-0.92504762,  0.73470188,  1.3277613 ,  2.08465352],
       [ 1.09757334,  0.20073398, -0.69800706, -0.15377675]])

In [26]:
np.random.randint(2,100)

47

In [28]:
np.random.randint(0,11,20)

array([ 5,  8,  3,  8,  4,  7,  4,  4,  6,  4,  5,  0,  6, 10,  4,  4,  9,
        1,  3,  1])

In [34]:
arrar=np.arange(10,25)
arrar


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
arrar[1:6]

array([11, 12, 13, 14, 15])

In [36]:
arrar[0]

10

In [37]:
arrar[0:9]

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [38]:
sub_array=arrar[0:9]
sub_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [40]:
sub_array[:]=999
sub_array

array([999, 999, 999, 999, 999, 999, 999, 999, 999])

In [41]:
sub_array[1:5]=2
sub_array

array([999,   2,   2,   2,   2, 999, 999, 999, 999])

In [49]:
a.T

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])